version: '3.4'

services:
  productsmanagement:
    image: docker-productsmanagement-productsmanagement
    container_name: productsmanagement
    build:
      context: .
      dockerfile: productsmanagement/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProductContext=Server=db;Database=master;User=sa;Password=YourStrong!Passw0rd;Encrypt=False;

  db:
    image: mcr.microsoft.com/mssql/server    
    container_name: productsmanagement-mssql
    hostname: productsmanagement-mssql    
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
